const stockProductos = [{
        imagen: "imagenes/camisetakobe.jpg",
        nombre: "Camiseta Lakers BlackMamba",
        vendedor: "Nike",
        precio: "$15000",
        id: 1,
    },
    {
        imagen: "imagenes/camisetamanu.jpg",
        nombre: "Camiseta Spurs Ginobili",
        vendedor: "Nike",
        precio: "$15000",
        id: 2,
    },
    {
        imagen: "imagenes/curry.jpg",
        nombre: "Camiseta GSW Curry",
        vendedor: "Nike",
        precio: "$15000",
        id: 3,
    },
    {
        imagen: "imagenes/harden.jpg",
        nombre: "Camiseta Rockets Harden",
        vendedor: "Nike",
        precio: "$15000",
        id: 4,
    },
    {
        imagen: "imagenes/camperakobe.jpg",
        nombre: "Campera Lakers Kobe Bryant",
        vendedor: "Nike",
        precio: "$16000",
        id: 5,
    },
    {
        imagen: "imagenes/gorra.jpg",
        nombre: "Gorra Bulls Blanca",
        vendedor: "Nike",
        precio: "$6000",
        id: 6,
    },
    {
        imagen: "imagenes/kobeFS.jpg",
        nombre: "Finger sleeve Kobe",
        vendedor: "Nike",
        precio: "$4000",
        id: 7,
    },
    {
        imagen: "imagenes/ZapasKobe8.jpg",
        nombre: "Zoom Kobe 6 Black Yellow",
        vendedor: "Nike",
        precio: "$16000",
        id: 8,
    },
    {
        imagen: "imagenes/kobesleeve.jpg",
        nombre: "Arm sleeve Kobe",
        vendedor: "Nike",
        precio: "$5000",
        id: 9,
    },
    {
        imagen: "imagenes/pelota.jpg",
        nombre: "Pelota Spalding Oficial NBA",
        vendedor: "Nike",
        precio: "$14000",
        id: 10,
    },
    {
        imagen: "imagenes/zapas.jpg",
        nombre: "AD Lakers",
        vendedor: "Nike",
        precio: "$10000",
        id: 11,
    },
    {
        imagen: "imagenes/zapas2.jpg",
        nombre: "Proto5 Lakers",
        vendedor: "Nike",
        precio: "$10000",
        id: 12,
    },
    {
        imagen: "imagenes/ZapasKobe3.jpg",
        nombre: "Mamba Instinct",
        vendedor: "Nike",
        precio: "$10000",
        id: 13,
    },
    {
        imagen: "imagenes/ZapasKobe4.jpg",
        nombre: "Mamba Focus",
        vendedor: "Nike",
        precio: "$10000",
        id: 14,
    },
    {
        imagen: "imagenes/ZapasKobe5.jpg",
        nombre: "Zoom Kobe Venom",
        vendedor: "Nike",
        precio: "$10000",
        id: 15,
    },
    {
        imagen: "imagenes/ZapasKobe6.jpg",
        nombre: "AD nxt 360",
        vendedor: "Nike",
        precio: "$10000",
        id: 16,
    },
    {
        imagen: "../imagenes/mochila.jpg",
        nombre: "Mochila Golden State",
        vendedor: "Nike",
        precio: "$7000",
        id: 17,
    },
    {
        imagen: "imagenes/shortAS.jpg",
        nombre: "Short All Star",
        vendedor: "Nike",
        precio: "$8000",
        id: 18,
    },
    {
        imagen: "imagenes/lebron17.jpg",
        nombre: "Lebron 17",
        vendedor: "Nike",
        precio: "$10000",
        id: 19,
    },
    {
        imagen: "imagenes/camperagsw.jpg",
        nombre: "Campera Golden State",
        vendedor: "Nike",
        precio: "$11000",
        id: 20,
    },
];